### ISSUE TITLE
Code review: separation of responsibilities

### ISSUE THREAD

**Issue by milenaalcantara** [lvasantos/DigiData#2]
https://github.com/lvasantos/DigiData/blob/5368bc14d895315e0114ecde465cbd5407545f58/IndividualChallenge/View/Core/Detail/DigimonCardView.swift#L288-L302

Oii, Lu ❤️

Tudo belezinha??
Vi aqui que tu tem uma extensão da UIImageView dentro do arquivo onde tu customiza teu card. Acredito que seria interessante tu colocar esse trecho de código em um arquivo separado, podendo até criar uma pastinha para extensions se tu achar melhor pra tua organização ☺️

Quando tu separar em um arquivo o xcode vai reclamar, mas aí é só tu importar o UIKit que ele para, belezinha?

Sugestão de arquitetura de pastas:
```shell
.
├── Resources
├── Extensions
    └── UIImageView.swift
├── Managers
├── Model
.
.
.
```

Qualquer coisinha só chamar =)

**Comment by lvasantos** [comment]
Oi, Milena !
Obrigada pela sugestão de organização de pastas ! ☺️
